(function(){
  const T={
    es:{
      home:'Inicio',onair:'On-Air',tv:'RFM TV',contact:'Contacto',about:'Sobre nosotros',
      listen:'Escuchar RFM',meet:'Conócenos',
      'hero.lead':'La mezcla perfecta entre nostalgia, energía latina y noches de neón. Clásicos que nunca pasan de moda, pop, rock, reggaetón y electrónica.',
      'hero.listen':'Escuchar RFM','hero.about':'Conócenos','stats.signal':'Señal digital','stats.nostalgia':'La nostalgia vive','stats.heart':'Desde nuestro corazón',
      'schedule.lead':'Descubre nuestros espacios, horarios y especiales directamente desde On-Air.',
      'feature.text':'El mood de RFM vive entre palmeras, Discmans, neón y canciones que te saben a carretera de noche. Somos una radio digital con identidad propia, nostalgia, actualidad y sabor latino.',
      'feature.contact':'Síguenos en redes','contact.lead':'Saludos, sugerencias, dedicatorias y todo lo que quieras compartir con la radio.','contact.button':'Contáctanos',
      'tv.digital':'RFM DIGITAL','tv.lead':'Tu ventana visual a Rhythm FM Latino. Este espacio queda preparado para conectar el canal de YouTube, una señal de video en vivo, videoclips, especiales y contenido original de RFM.','tv.home':'Volver al Home','tv.youtube':'Abrir canal de YouTube ↗',
      contactTitle:'Contáctanos',contactDesc:'Saludos, sugerencias o mensajes para la radio en vivo.',name:'Nombre',email:'Correo electrónico',type:'Tipo de mensaje',message:'Mensaje',send:'Enviar mensaje',
      aboutTitle2:'Sobre RhythmFM Latino',aboutIntro:'Una estación digital enfocada en música adulta contemporánea, con una selección cuidada desde los 80 hasta hoy.',
      aboutWho:'Quiénes somos',aboutWhoText:'RhythmFM Latino es una emisora online con selección curada de pop, R&B, dance y sonidos urbanos desde los 80 hasta hoy, con un enfoque adulto contemporáneo y una estética digital moderna.',aboutProgramming:'Nuestra programación',aboutProgrammingText:'Combinamos clásicos y hits actuales para una experiencia continua: elegante, energética y sin ruido innecesario.',aboutDigital:'Experiencia digital',aboutDigitalText:'Streaming en tiempo real, identificación automática de canciones y acceso desde diferentes dispositivos.',aboutNetwork:'myGochez Network International™',aboutNetworkText:'RhythmFM Latino forma parte de myGochez Network International, una iniciativa enfocada en plataformas digitales y experiencias multimedia.',aboutQuote:'“Si hay internet, hay RhythmFM.”',aboutNetworkSub:'Radio, streaming y productos web construidos para conectar con oyentes de cualquier lugar.',aboutLegal:'Información legal',aboutLegalSub:'Estas páginas forman parte de la identidad institucional de RhythmFM Latino y myGochez Network International™.',
      hablemos:'Hablemos',contactBody:'Puedes enviarnos saludos al aire, sugerencias, reportes técnicos u otro mensaje. Conservamos el formulario y el flujo de respuesta de tu sitio actual.',contactNotice:'También puedes encontrarnos en nuestras redes sociales y a través de RFM TV.',explore:'Explora',legal:'Legal',
      terms:'Términos de uso',privacy:'Política de privacidad',cookies:'Política de cookies',copyright:'Derechos de autor',privacyShort:'Privacidad',cookiesShort:'Cookies',termsShort:'Términos',copyrightShort:'Derechos de autor',
      thanks:'¡Gracias!',thanksText:'Tu mensaje fue enviado correctamente. Nos pondremos en contacto contigo cuando sea necesario.',thanksBack:'Volver al sitio',
      program:'Programación',programLead:'La programación actualizada de la radio. Aquí podemos incorporar horarios, programas, especiales y próximos contenidos.',weekday:'LUNES · VIERNES',allDay:'TODO EL DÍA',nights:'NOCHES',rhythmMorning:'Rhythm Morning',morningText:'Clásicos, pop y energía para comenzar el día.',rhythmMix:'Rhythm Mix',mixText:'Una mezcla continua de grandes éxitos y favoritos del público.',afterDark:'After Dark',afterDarkText:'R&B, dance, pop nocturno y sonidos urbanos.',
      styles:'Estilos',stylesLead:'La personalidad de RFM vive en una mezcla de décadas y géneros.',popClassics:'Pop & Classics',popClassicsText:'Himnos, synth-pop y canciones que construyeron una generación.',vibes90:'90s Vibes',vibes90Text:'Pop, R&B, dance y favoritos noventeros.',modernRhythm:'Modern Rhythm',modernRhythmText:'Hits actuales, urbanos, dance y una selección adulta contemporánea.',curatedSound:'SONIDO CURADO',
      station:'Estación',mood:'Mood',live:'EN VIVO',nowPlaying:'Ahora suena',loadingSong:'Cargando canción…',refreshEvery:'Se actualiza cada 12 segundos.',refresh:'🔄 Refrescar',neonNow:'Neon Player • Now Playing en tiempo real',
      onairTitle:'On-Air',onairDesc:'Escucha RhythmFM Latino en vivo desde cualquier dispositivo.',
      footerLine:'Una radio de myGochez Network International™',rights:'Todos los derechos reservados.',brandLegal:'RhythmFM Latino™ · Una radio de myGochez Network International™ · Todos los derechos reservados.',
      digital:'Señal digital',nostalgia:'La nostalgia vive',latino:'Desde nuestro corazón',
      legal_terms_h1:'Uso del sitio',legal_terms_p1:'El acceso y uso de este sitio implica la aceptación de estos términos. RhythmFM Latino y myGochez Network International™ pueden actualizar contenidos, servicios o enlaces cuando sea necesario.',legal_terms_h2:'Contenido y servicio',legal_terms_p2:'La señal de radio se ofrece por streaming y puede estar sujeta a interrupciones, mantenimiento, disponibilidad de terceros o condiciones de internet. No se garantiza disponibilidad continua.',legal_terms_h3:'Uso responsable',legal_terms_p3:'No se permite utilizar el sitio para actividades ilícitas, para interferir con su funcionamiento o para intentar obtener acceso no autorizado a sus sistemas.',
      legal_priv_h1:'Información que recibimos',legal_priv_p1:'El formulario de contacto puede recopilar nombre, correo electrónico y el contenido que el visitante decida enviar. Estos datos se usan para responder consultas, saludos, sugerencias o reportes.',legal_priv_h2:'Proveedores',legal_priv_p2:'El procesamiento del formulario puede realizarse mediante un proveedor externo como Formspree. Los servicios de streaming también pueden utilizar infraestructura de terceros.',legal_priv_h3:'Conservación',legal_priv_p3:'Solo debe conservarse la información durante el tiempo razonablemente necesario para atender la comunicación y cumplir obligaciones aplicables.',
      legal_cookie_h1:'Cookies y almacenamiento local',legal_cookie_p1:'El sitio puede usar almacenamiento local del navegador para recordar el idioma seleccionado y preferencias visuales. Esto permite que la experiencia se mantenga entre páginas.',legal_cookie_h2:'Terceros',legal_cookie_p2:'Servicios externos, como el reproductor de streaming, YouTube o herramientas de analítica si se incorporan posteriormente, pueden utilizar sus propias cookies o tecnologías similares.',legal_cookie_h3:'Control del usuario',legal_cookie_p3:'El visitante puede borrar o bloquear cookies y almacenamiento local desde la configuración de su navegador.',
      legal_copy_h1:'Marca y diseño',legal_copy_p1:'RhythmFM Latino™, RFM y los elementos visuales asociados pertenecen a sus respectivos titulares y no deben reproducirse comercialmente sin autorización.',legal_copy_h2:'Música y contenidos',legal_copy_p2:'Las grabaciones, composiciones y demás contenidos musicales pertenecen a sus respectivos titulares. La disponibilidad de la señal depende de las licencias y derechos aplicables a la operación de la emisora.',legal_copy_h3:'Aviso',legal_copy_p3:'Este texto es informativo y no sustituye asesoría legal sobre licencias, derechos de comunicación pública o requisitos regulatorios en una jurisdicción determinada.'
    },
    en:{
      home:'Home',onair:'On-Air',tv:'RFM TV',contact:'Contact',about:'About',listen:'Listen to RFM',meet:'Discover us',
      'hero.lead':'The perfect mix of nostalgia, Latin energy and neon nights. Timeless classics, pop, rock, reggaeton and electronic sounds.',
      'hero.listen':'Listen to RFM','hero.about':'Discover us','stats.signal':'Digital signal','stats.nostalgia':'Nostalgia lives','stats.heart':'From our heart',
      'schedule.lead':'Discover our shows, schedules and specials directly from On-Air.',
      'feature.text':'RFM lives among palm trees, Discmans, neon and songs that feel like a night drive. A digital radio with its own identity, nostalgia, today and Latin flavor.',
      'feature.contact':'Follow us on social','contact.lead':'Greetings, suggestions, dedications and everything you would like to share with the station.','contact.button':'Contact us',
      'tv.digital':'RFM DIGITAL','tv.lead':'Your visual window into Rhythm FM Latino. This space is ready for the YouTube channel, a live video signal, music videos, specials and original RFM content.','tv.home':'Back to Home','tv.youtube':'Open YouTube channel ↗',
      contactTitle:'Contact us',contactDesc:'Greetings, suggestions or messages for the live radio team.',name:'Name',email:'Email',type:'Message type',message:'Message',send:'Send message',
      aboutTitle2:'About RhythmFM Latino',aboutIntro:'A digital station focused on adult-contemporary music, with a curated selection from the 80s to today.',
      aboutWho:'Who we are',aboutWhoText:'RhythmFM Latino is an online station with a curated selection of pop, R&B, dance and urban sounds from the 80s to today, with an adult-contemporary focus and a modern digital aesthetic.',aboutProgramming:'Our programming',aboutProgrammingText:'We combine classics and current hits for a continuous experience: elegant, energetic and free from unnecessary noise.',aboutDigital:'Digital experience',aboutDigitalText:'Real-time streaming, automatic song identification and access from different devices.',aboutNetwork:'myGochez Network International™',aboutNetworkText:'RhythmFM Latino is part of myGochez Network International, an initiative focused on digital platforms and multimedia experiences.',aboutQuote:'“If there is internet, there is RhythmFM.”',aboutNetworkSub:'Radio, streaming and web products built to connect with listeners anywhere.',aboutLegal:'Legal information',aboutLegalSub:'These pages are part of the institutional identity of RhythmFM Latino and myGochez Network International™.',
      hablemos:'Let’s talk',contactBody:'Send on-air greetings, suggestions, technical reports or another message. We kept the form and response flow from your current site.',contactNotice:'You can also find us on our social networks and through RFM TV.',explore:'Explore',legal:'Legal',
      terms:'Terms of use',privacy:'Privacy policy',cookies:'Cookie policy',copyright:'Copyright',privacyShort:'Privacy',cookiesShort:'Cookies',termsShort:'Terms',copyrightShort:'Copyright',
      thanks:'Thank you!',thanksText:'Your message was sent successfully. We will contact you when necessary.',thanksBack:'Back to site',
      program:'Schedule',programLead:'The station’s current schedule. Here we can include times, shows, specials and upcoming content.',weekday:'MONDAY · FRIDAY',allDay:'ALL DAY',nights:'NIGHTS',rhythmMorning:'Rhythm Morning',morningText:'Classics, pop and energy to start the day.',rhythmMix:'Rhythm Mix',mixText:'A continuous mix of great hits and audience favorites.',afterDark:'After Dark',afterDarkText:'R&B, dance, late-night pop and urban sounds.',
      styles:'Music',stylesLead:'RFM personality lives in a mix of decades and genres.',popClassics:'Pop & Classics',popClassicsText:'Anthems, synth-pop and songs that shaped a generation.',vibes90:'90s Vibes',vibes90Text:'Pop, R&B, dance and favorite 90s tracks.',modernRhythm:'Modern Rhythm',modernRhythmText:'Current hits, urban, dance and a curated adult-contemporary selection.',curatedSound:'CURATED SOUND',
      station:'Station',mood:'Mood',live:'LIVE',nowPlaying:'Now Playing',loadingSong:'Loading song…',refreshEvery:'Updates every 12 seconds.',refresh:'🔄 Refresh',neonNow:'Neon Player • Real-time Now Playing',
      onairTitle:'On-Air',onairDesc:'Listen to RhythmFM Latino live from any device.',
      footerLine:'A myGochez Network International™ radio',rights:'All rights reserved.',brandLegal:'RhythmFM Latino™ · A myGochez Network International™ radio · All rights reserved.',
      digital:'Digital signal',nostalgia:'Nostalgia lives',latino:'From our heart',
      legal_terms_h1:'Site use',legal_terms_p1:'Access to and use of this site implies acceptance of these terms. RhythmFM Latino and myGochez Network International™ may update content, services or links when necessary.',legal_terms_h2:'Content and service',legal_terms_p2:'The radio stream is provided online and may be affected by interruptions, maintenance, third-party availability or internet conditions. Continuous availability is not guaranteed.',legal_terms_h3:'Responsible use',legal_terms_p3:'You may not use the site for unlawful activities, interfere with its operation or attempt unauthorized access to its systems.',
      legal_priv_h1:'Information we receive',legal_priv_p1:'The contact form may collect your name, email address and the content you choose to send. This information is used to respond to inquiries, greetings, suggestions or reports.',legal_priv_h2:'Providers',legal_priv_p2:'Form submissions may be processed by an external provider such as Formspree. Streaming services may also rely on third-party infrastructure.',legal_priv_h3:'Retention',legal_priv_p3:'Information should only be retained for as long as reasonably necessary to handle the communication and meet applicable obligations.',
      legal_cookie_h1:'Cookies and local storage',legal_cookie_p1:'The site may use browser local storage to remember your selected language and visual preferences. This keeps the experience consistent across pages.',legal_cookie_h2:'Third parties',legal_cookie_p2:'External services such as the streaming player, YouTube or analytics tools, if added later, may use their own cookies or similar technologies.',legal_cookie_h3:'Your controls',legal_cookie_p3:'You can delete or block cookies and local storage from your browser settings.',
      legal_copy_h1:'Brand and design',legal_copy_p1:'RhythmFM Latino™, RFM and associated visual elements belong to their respective rights holders and may not be commercially reproduced without authorization.',legal_copy_h2:'Music and content',legal_copy_p2:'Sound recordings, compositions and other music content belong to their respective rights holders. Availability of the stream depends on the licenses and rights applicable to the station’s operation.',legal_copy_h3:'Notice',legal_copy_p3:'This text is informational and does not replace legal advice about licenses, public-performance rights or regulatory requirements in a specific jurisdiction.'
    },
    pt:{
      home:'Início',onair:'On-Air',tv:'RFM TV',contact:'Contato',about:'Sobre nós',listen:'Ouvir RFM',meet:'Conheça-nos',
      'hero.lead':'A mistura perfeita de nostalgia, energia latina e noites de neon. Clássicos atemporais, pop, rock, reggaeton e eletrônica.',
      'hero.listen':'Ouvir RFM','hero.about':'Conheça-nos','stats.signal':'Sinal digital','stats.nostalgia':'A nostalgia vive','stats.heart':'Do nosso coração',
      'schedule.lead':'Descubra nossos programas, horários e especiais diretamente no On-Air.',
      'feature.text':'O clima da RFM vive entre palmeiras, Discman, neon e músicas que lembram uma estrada noturna. Uma rádio digital com identidade própria, nostalgia, atualidade e sabor latino.',
      'feature.contact':'Siga-nos nas redes','contact.lead':'Saudações, sugestões, dedicatórias e tudo o que você quiser compartilhar com a rádio.','contact.button':'Fale conosco',
      'tv.digital':'RFM DIGITAL','tv.lead':'Sua janela visual para a Rhythm FM Latino. Este espaço está preparado para conectar o canal do YouTube, um sinal de vídeo ao vivo, videoclipes, especiais e conteúdo original da RFM.','tv.home':'Voltar ao Início','tv.youtube':'Abrir canal do YouTube ↗',
      contactTitle:'Fale conosco',contactDesc:'Saudações, sugestões ou mensagens para a equipe da rádio ao vivo.',name:'Nome',email:'E-mail',type:'Tipo de mensagem',message:'Mensagem',send:'Enviar mensagem',
      aboutTitle2:'Sobre a RhythmFM Latino',aboutIntro:'Uma estação digital focada em música adulta contemporânea, com seleção curada dos anos 80 até hoje.',
      aboutWho:'Quem somos',aboutWhoText:'RhythmFM Latino é uma emissora online com seleção curada de pop, R&B, dance e sons urbanos dos anos 80 até hoje, com foco adulto contemporâneo e estética digital moderna.',aboutProgramming:'Nossa programação',aboutProgrammingText:'Combinamos clássicos e sucessos atuais para uma experiência contínua: elegante, energética e sem ruído desnecessário.',aboutDigital:'Experiência digital',aboutDigitalText:'Streaming em tempo real, identificação automática de músicas e acesso a partir de diferentes dispositivos.',aboutNetwork:'myGochez Network International™',aboutNetworkText:'A RhythmFM Latino faz parte da myGochez Network International, uma iniciativa focada em plataformas digitais e experiências multimídia.',aboutQuote:'“Se há internet, há RhythmFM.”',aboutNetworkSub:'Rádio, streaming e produtos web feitos para conectar ouvintes de qualquer lugar.',aboutLegal:'Informação legal',aboutLegalSub:'Estas páginas fazem parte da identidade institucional da RhythmFM Latino e da myGochez Network International™.',
      hablemos:'Vamos conversar',contactBody:'Envie saudações para o ar, sugestões, relatórios técnicos ou outra mensagem. Mantivemos o formulário e o fluxo de resposta do seu site atual.',contactNotice:'Você também pode nos encontrar nas redes sociais e através da RFM TV.',explore:'Explore',legal:'Legal',
      terms:'Termos de uso',privacy:'Política de privacidade',cookies:'Política de cookies',copyright:'Direitos autorais',privacyShort:'Privacidade',cookiesShort:'Cookies',termsShort:'Termos',copyrightShort:'Direitos autorais',
      thanks:'Obrigado!',thanksText:'Sua mensagem foi enviada com sucesso. Entraremos em contato quando necessário.',thanksBack:'Voltar ao site',
      program:'Programação',programLead:'A programação atual da rádio. Aqui podemos incluir horários, programas, especiais e próximos conteúdos.',weekday:'SEGUNDA · SEXTA',allDay:'TODO O DIA',nights:'NOITES',rhythmMorning:'Rhythm Morning',morningText:'Clássicos, pop e energia para começar o dia.',rhythmMix:'Rhythm Mix',mixText:'Uma mistura contínua de grandes sucessos e favoritos do público.',afterDark:'After Dark',afterDarkText:'R&B, dance, pop noturno e sons urbanos.',
      styles:'Estilos',stylesLead:'A personalidade da RFM vive em uma mistura de décadas e gêneros.',popClassics:'Pop & Classics',popClassicsText:'Hinos, synth-pop e músicas que marcaram uma geração.',vibes90:'90s Vibes',vibes90Text:'Pop, R&B, dance e favoritos dos anos 90.',modernRhythm:'Modern Rhythm',modernRhythmText:'Hits atuais, urbanos, dance e uma seleção adulta contemporânea.',curatedSound:'SOM CURADO',
      station:'Estação',mood:'Mood',live:'AO VIVO',nowPlaying:'Agora tocando',loadingSong:'Carregando música…',refreshEvery:'Atualiza a cada 12 segundos.',refresh:'🔄 Atualizar',neonNow:'Neon Player • Now Playing em tempo real',
      onairTitle:'On-Air',onairDesc:'Ouça a RhythmFM Latino ao vivo em qualquer dispositivo.',
      footerLine:'Uma rádio da myGochez Network International™',rights:'Todos os direitos reservados.',brandLegal:'RhythmFM Latino™ · Uma rádio da myGochez Network International™ · Todos os direitos reservados.',
      digital:'Sinal digital',nostalgia:'A nostalgia vive',latino:'Do nosso coração',
      legal_terms_h1:'Uso do site',legal_terms_p1:'O acesso e uso deste site implica a aceitação destes termos. A RhythmFM Latino e a myGochez Network International™ podem atualizar conteúdos, serviços ou links quando necessário.',legal_terms_h2:'Conteúdo e serviço',legal_terms_p2:'A transmissão de rádio é oferecida por streaming e pode sofrer interrupções, manutenção, disponibilidade de terceiros ou condições da internet. A disponibilidade contínua não é garantida.',legal_terms_h3:'Uso responsável',legal_terms_p3:'Não é permitido usar o site para atividades ilícitas, interferir em seu funcionamento ou tentar obter acesso não autorizado aos seus sistemas.',
      legal_priv_h1:'Informações que recebemos',legal_priv_p1:'O formulário de contato pode coletar nome, e-mail e o conteúdo que o visitante decidir enviar. Esses dados são usados para responder dúvidas, saudações, sugestões ou relatos.',legal_priv_h2:'Provedores',legal_priv_p2:'O processamento do formulário pode ser realizado por um provedor externo como o Formspree. Os serviços de streaming também podem utilizar infraestrutura de terceiros.',legal_priv_h3:'Retenção',legal_priv_p3:'As informações devem ser mantidas apenas pelo tempo razoavelmente necessário para atender à comunicação e cumprir obrigações aplicáveis.',
      legal_cookie_h1:'Cookies e armazenamento local',legal_cookie_p1:'O site pode usar o armazenamento local do navegador para lembrar o idioma selecionado e preferências visuais. Isso mantém a experiência consistente entre as páginas.',legal_cookie_h2:'Terceiros',legal_cookie_p2:'Serviços externos, como o player de streaming, YouTube ou ferramentas de análise, se forem adicionados posteriormente, podem usar seus próprios cookies ou tecnologias semelhantes.',legal_cookie_h3:'Controle do usuário',legal_cookie_p3:'O visitante pode apagar ou bloquear cookies e armazenamento local nas configurações do navegador.',
      legal_copy_h1:'Marca e design',legal_copy_p1:'RhythmFM Latino™, RFM e os elementos visuais associados pertencem aos seus respectivos titulares e não devem ser reproduzidos comercialmente sem autorização.',legal_copy_h2:'Música e conteúdo',legal_copy_p2:'As gravações, composições e demais conteúdos musicais pertencem aos seus respectivos titulares. A disponibilidade do sinal depende das licenças e direitos aplicáveis à operação da emissora.',legal_copy_h3:'Aviso',legal_copy_p3:'Este texto é informativo e não substitui orientação jurídica sobre licenças, direitos de comunicação pública ou requisitos regulatórios em uma jurisdição específica.'
    }
  };
  const pageTitles={
    index:{es:'RhythmFM Latino — Tu ritmo, tu radio',en:'RhythmFM Latino — Your rhythm, your radio',pt:'RhythmFM Latino — Seu ritmo, sua rádio'},
    onair:{es:'On-Air | RhythmFM Latino',en:'On-Air | RhythmFM Latino',pt:'On-Air | RhythmFM Latino'},
    tv:{es:'RFM TV — Rhythm FM Latino',en:'RFM TV — Rhythm FM Latino',pt:'RFM TV — Rhythm FM Latino'},
    contact:{es:'Contáctanos | RhythmFM Latino',en:'Contact us | RhythmFM Latino',pt:'Fale conosco | RhythmFM Latino'},
    about:{es:'Sobre nosotros | RhythmFM Latino',en:'About us | RhythmFM Latino',pt:'Sobre nós | RhythmFM Latino'},
    thanks:{es:'Gracias | RhythmFM Latino',en:'Thank you | RhythmFM Latino',pt:'Obrigado | RhythmFM Latino'},
    program:{es:'Programación | RhythmFM Latino',en:'Schedule | RhythmFM Latino',pt:'Programação | RhythmFM Latino'},
    styles:{es:'Estilos | RhythmFM Latino',en:'Music | RhythmFM Latino',pt:'Estilos | RhythmFM Latino'},
    legal:{es:'Información legal | RhythmFM Latino',en:'Legal information | RhythmFM Latino',pt:'Informação legal | RhythmFM Latino'}
  };
  const EXTRA={
    es:{eighties:'80s',nineties:'90s',twoKToday:'2000s → HOY',legalBrand:'RhythmFM Latino™ · myGochez Network International™',legalNotice:'Última actualización: agosto de 2026. Este documento puede requerir adaptación a la jurisdicción y modelo de operación de la emisora.',
      'social.instagram':'Instagram','social.facebook':'Facebook','social.whatsapp':'WhatsApp','social.email':'Correo','hero.eyebrow':'80s · 90s · Y MÁS','ticker1':'✦ 80s & 90s','ticker2':'✦ POP & ROCK','ticker3':'✦ REGGAETÓN','ticker4':'✦ ELECTRÓNICA','ticker5':'✦ CLÁSICOS','ticker6':'✦ LATINO','schedule.title':'Una radio que siempre suena.','schedule.kicker':'LA PROGRAMACIÓN','adn.kicker':'EL ADN DE RFM','adn.title':'Sonidos con personalidad.','feature.kicker':'RFM ORIGINAL','contact.kicker':'CONECTEMOS','social.title':'RFM SOCIAL CLUB',time1:'06:00 — 10:00',rhythmMorning:'RFM Sunrise',morningHomeText:'Pop, classics and energy to start the day.',morningBadge:'MORNING',time2:'10:00 — 14:00',retroMix:'Retro Mix',retroMixText:'80s and 90s anthems that are still alive.',retroBadge:'80s · 90s',time3:'14:00 — 18:00',latinoBeat:'Latino Beat',latinoBeatText:'Reggaeton, Latin pop and your favorites.',latinoBadge:'LATIN',time4:'18:00 — 00:00',neonNights:'Neon Nights',neonNightsText:'Electronic, synthwave and nighttime classics.',nightBadge:'NIGHT'},
    en:{eighties:'80s',nineties:'90s',twoKToday:'2000s → TODAY',legalBrand:'RhythmFM Latino™ · myGochez Network International™',legalNotice:'Last updated: August 2026. This document may require adaptation to the station’s jurisdiction and operating model.',
      'social.instagram':'Instagram','social.facebook':'Facebook','social.whatsapp':'WhatsApp','social.email':'Email','hero.eyebrow':'80s · 90s · AND MORE','ticker1':'✦ 80s & 90s','ticker2':'✦ POP & ROCK','ticker3':'✦ REGGAETON','ticker4':'✦ ELECTRONIC','ticker5':'✦ CLASSICS','ticker6':'✦ LATIN','schedule.title':'A radio that always sounds.','schedule.kicker':'THE SCHEDULE','adn.kicker':'RFM DNA','adn.title':'Sounds with personality.','feature.kicker':'RFM ORIGINAL','contact.kicker':'LET’S CONNECT','social.title':'RFM SOCIAL CLUB',time1:'06:00 — 10:00',rhythmMorning:'RFM Sunrise',morningHomeText:'Pop, classics and energy to start the day.',morningBadge:'MORNING',time2:'10:00 — 14:00',retroMix:'Retro Mix',retroMixText:'80s and 90s anthems that are still alive.',retroBadge:'80s · 90s',time3:'14:00 — 18:00',latinoBeat:'Latino Beat',latinoBeatText:'Reggaeton, Latin pop and your favorites.',latinoBadge:'LATIN',time4:'18:00 — 00:00',neonNights:'Neon Nights',neonNightsText:'Electronic, synthwave and nighttime classics.',nightBadge:'NIGHT'},
    pt:{eighties:'80s',nineties:'90s',twoKToday:'2000s → HOJE',legalBrand:'RhythmFM Latino™ · myGochez Network International™',legalNotice:'Última atualização: agosto de 2026. Este documento pode exigir adaptação à jurisdição e ao modelo de operação da emissora.',
      'social.instagram':'Instagram','social.facebook':'Facebook','social.whatsapp':'WhatsApp','social.email':'E-mail','hero.eyebrow':'80s · 90s · E MAIS','ticker1':'✦ 80s & 90s','ticker2':'✦ POP & ROCK','ticker3':'✦ REGGAETON','ticker4':'✦ ELETRÔNICA','ticker5':'✦ CLÁSSICOS','ticker6':'✦ LATINO','schedule.title':'Uma rádio que sempre toca.','schedule.kicker':'A PROGRAMAÇÃO','adn.kicker':'O DNA DA RFM','adn.title':'Sons com personalidade.','feature.kicker':'RFM ORIGINAL','contact.kicker':'VAMOS CONECTAR','social.title':'RFM SOCIAL CLUB'}
  };
  Object.keys(EXTRA).forEach(l=>Object.assign(T[l],EXTRA[l]));

  Object.assign(T.es,{footerTagline:'TU RITMO, TU RADIO'}); Object.assign(T.en,{footerTagline:'YOUR RHYTHM, YOUR RADIO'}); Object.assign(T.pt,{footerTagline:'SEU RITMO, SUA RÁDIO'});
  const HOME_EXTRA={es:{heroTitle1:'Tu ritmo,',heroTitle2:'tu radio.',scheduleTitle1:'Una radio que',scheduleTitle2:'siempre suena.',adnTitle1:'Sonidos con',adnTitle2:'personalidad.',featureTitle1:'Una vibra que',featureTitle2:'se reconoce.',contactTitle1:'Haz ruido.',contactTitle2:'Quédate en RFM.',cassetteFooter:'SIDE A · SIDE B',optionGreeting:'Saludo al aire 🎙️',optionSuggestion:'Sugerencia',optionReport:'Reporte técnico',optionOther:'Otro',time1:'06:00 — 10:00',rhythmMorning:'RFM Sunrise',morningHomeText:'Pop, clásicos y energía para arrancar el día.',morningBadge:'MAÑANA',time2:'10:00 — 14:00',retroMix:'Retro Mix',retroMixText:'Los himnos 80s y 90s que siguen vivos.',retroBadge:'80s · 90s',time3:'14:00 — 18:00',latinoBeat:'Latino Beat',latinoBeatText:'Reggaetón, pop latino y tus favoritos.',latinoBadge:'LATINO',time4:'18:00 — 00:00',neonNights:'Neon Nights',neonNightsText:'Electrónica, synthwave y clásicos nocturnos.',nightBadge:'NOCHE'},en:{heroTitle1:'Your rhythm,',heroTitle2:'your radio.',scheduleTitle1:'A radio that',scheduleTitle2:'always sounds.',adnTitle1:'Sounds with',adnTitle2:'personality.',featureTitle1:'A vibe that',featureTitle2:'stands out.',contactTitle1:'Make some noise.',contactTitle2:'Stay with RFM.',cassetteFooter:'SIDE A · SIDE B',optionGreeting:'On-air greeting 🎙️',optionSuggestion:'Suggestion',optionReport:'Technical report',optionOther:'Other',time1:'06:00 — 10:00',rhythmMorning:'RFM Sunrise',morningHomeText:'Pop, classics and energy to start the day.',morningBadge:'MORNING',time2:'10:00 — 14:00',retroMix:'Retro Mix',retroMixText:'80s and 90s anthems that are still alive.',retroBadge:'80s · 90s',time3:'14:00 — 18:00',latinoBeat:'Latino Beat',latinoBeatText:'Reggaeton, Latin pop and your favorites.',latinoBadge:'LATIN',time4:'18:00 — 00:00',neonNights:'Neon Nights',neonNightsText:'Electronic, synthwave and nighttime classics.',nightBadge:'NIGHT'},pt:{heroTitle1:'Seu ritmo,',heroTitle2:'sua rádio.',scheduleTitle1:'Uma rádio que',scheduleTitle2:'sempre toca.',adnTitle1:'Sons com',adnTitle2:'personalidade.',featureTitle1:'Uma vibe que',featureTitle2:'se reconhece.',contactTitle1:'Faça barulho.',contactTitle2:'Fique na RFM.',cassetteFooter:'LADO A · LADO B',optionGreeting:'Saudação ao vivo 🎙️',optionSuggestion:'Sugestão',optionReport:'Relato técnico',optionOther:'Outro',time1:'06:00 — 10:00',rhythmMorning:'RFM Sunrise',morningHomeText:'Pop, clássicos e energia para começar o dia.',morningBadge:'MANHÃ',time2:'10:00 — 14:00',retroMix:'Retro Mix',retroMixText:'Hinos dos anos 80 e 90 que continuam vivos.',retroBadge:'80s · 90s',time3:'14:00 — 18:00',latinoBeat:'Latino Beat',latinoBeatText:'Reggaeton, pop latino e seus favoritos.',latinoBadge:'LATINO',time4:'18:00 — 00:00',neonNights:'Neon Nights',neonNightsText:'Eletrônica, synthwave e clássicos noturnos.',nightBadge:'NOITE'}}; Object.keys(HOME_EXTRA).forEach(l=>Object.assign(T[l],HOME_EXTRA[l]));
  function pageKey(){
    const f=(location.pathname.split('/').pop()||'index.html').toLowerCase();
    if(f==='index.html'||f==='') return 'index'; if(f==='on-air.html') return 'onair'; if(f==='rfm-tv.html') return 'tv'; if(f==='contacto.html') return 'contact'; if(f==='gracias.html') return 'thanks'; if(f==='about.html') return 'about'; if(f==='programacion.html') return 'program'; if(f==='estilos.html') return 'styles'; return 'legal';
  }
  function setText(el,text){ if(el && text!=null){ el.textContent=text; } }
  function applyLang(lang){
    const l=T[lang]?lang:'es';
    document.documentElement.lang=l;
    const d=T[l];
    document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(d[k]!=null)setText(el,d[k]);});
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(d[k]!=null)el.setAttribute('placeholder',d[k]);});
    document.querySelectorAll('[data-rfm-i18n]').forEach(el=>{const k=el.dataset.rfmI18n;if(d[k]!=null)setText(el,d[k]);});
    document.querySelectorAll('[data-rfm-lang-label]').forEach(el=>setText(el,l==='es'?'Español':l==='en'?'English':'Português'));
    const pt=pageTitles[pageKey()]; if(pt) document.title=pt[l]||document.title;
    localStorage.setItem('rfm_lang',l);
    const hidden=document.getElementById('langHidden'); if(hidden) hidden.value=l;
    if(window.rfmPlayerLanguage) window.rfmPlayerLanguage(d);
  }
  window.RFM_I18N=T;
  window.rfmApplyPageLanguage=applyLang;
  window.rfmGetLanguage=()=>localStorage.getItem('rfm_lang')||((navigator.language||'es').toLowerCase().startsWith('pt')?'pt':(navigator.language||'es').toLowerCase().startsWith('en')?'en':'es');
  document.addEventListener('DOMContentLoaded',()=>applyLang(window.rfmGetLanguage()));
})();
